
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjut-training?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: wmy20011125528
    driver-class-name: com.mysql.cj.jdbc.Driver