server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zjut-training?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qq491705331
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations:
    - classpath*:mapper/**/*Mapper.xml